import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import AirdropPanel from '~/components/AirdropPanel'
import MediaList from '~/components/MediaList'

const AppContainer = styled.div`
  width: 100%;
  height: auto;
  min-height: 100vh;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
  background: url('/images/bg.png') top center no-repeat;
  background-size: 100% 100%;
`

const Title = styled.h1`
  font-family: 'SF Pro Text';
  font-style: normal;
  font-weight: 700;
  font-size: 36px;
  display: flex;
  align-items: center;
  color: #ffffff;
  text-shadow: 0px 4px 20px rgba(65, 230, 175, 0.6);
`

const Description = styled.div`
  font-family: 'SF Pro Text';
  font-style: normal;
  font-weight: 300;
  font-size: 14px;
  display: flex;
  align-items: center;
  color: #ffffff;
`

const Link = styled.a`
  color: #00d092;
  &:hover {
    color: #00d092;
  }
`

const Home: NextPage = () => {
  return (
    <AppContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="//recaptcha.net/recaptcha/api.js?hl=en"></script>
      </Head>
      <Image src="/images/kcc-logo.png" width={140} height={50} alt="kcc-logo" />
      <Title>KCC MAINNET FAUCET</Title>
      <Description>
        If you are using KCC-Faucet for the first time,you can &nbsp;<Link href=""> Check the guide</Link>
      </Description>
      <AirdropPanel />
      <MediaList />
    </AppContainer>
  )
}

export default Home
